"""External integrations — Hatchet, litellm, Langfuse (isolated layer)."""

from owlclaw.integrations.hatchet import HatchetClient, HatchetConfig
from owlclaw.integrations.hatchet_acceptance import (
    build_status_snapshot,
    evaluate_e2e_acceptance,
    verify_restart_recovery,
)
from owlclaw.integrations.hatchet_cutover import build_cutover_decision, normalize_scheduler_backend
from owlclaw.integrations.hatchet_migration import (
    APSchedulerJob,
    classify_job_complexity,
    dual_run_replay_compare,
    load_jobs_from_mionyee_scenarios,
    render_hatchet_module,
    render_hatchet_workflow,
    select_canary_batch,
    simulate_apscheduler_execution,
    simulate_hatchet_execution,
    split_jobs_by_complexity,
    write_complexity_modules,
    write_generated_hatchet_module,
)
from owlclaw.integrations.langfuse import (
    LangfuseClient,
    LangfuseConfig,
    LLMSpanData,
    PrivacyMasker,
    SpanType,
    TokenCalculator,
    ToolSpanData,
    TraceContext,
    TraceMetadata,
    load_langfuse_config,
    validate_config,
)
from owlclaw.integrations.llm import (
    AuthenticationError,
    ContextWindowExceededError,
    LLMClient,
    LLMConfig,
    LLMResponse,
    PromptBuilder,
    RateLimitError,
    ServiceUnavailableError,
    TokenEstimator,
    ToolsConverter,
    acompletion,
)

__all__ = [
    "HatchetClient",
    "HatchetConfig",
    "build_status_snapshot",
    "evaluate_e2e_acceptance",
    "verify_restart_recovery",
    "build_cutover_decision",
    "normalize_scheduler_backend",
    "APSchedulerJob",
    "classify_job_complexity",
    "dual_run_replay_compare",
    "load_jobs_from_mionyee_scenarios",
    "render_hatchet_module",
    "render_hatchet_workflow",
    "select_canary_batch",
    "simulate_apscheduler_execution",
    "simulate_hatchet_execution",
    "split_jobs_by_complexity",
    "write_complexity_modules",
    "write_generated_hatchet_module",
    "LLMSpanData",
    "LangfuseClient",
    "LangfuseConfig",
    "PrivacyMasker",
    "SpanType",
    "TokenCalculator",
    "ToolSpanData",
    "TraceContext",
    "TraceMetadata",
    "load_langfuse_config",
    "validate_config",
    "acompletion",
    "AuthenticationError",
    "ContextWindowExceededError",
    "LLMClient",
    "LLMConfig",
    "LLMResponse",
    "PromptBuilder",
    "RateLimitError",
    "ServiceUnavailableError",
    "TokenEstimator",
    "ToolsConverter",
]
