"""Load MCP tool definitions generated by `owlclaw migrate --output-mode mcp`."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from owlclaw.capabilities.registry import CapabilityRegistry


def register_generated_mcp_tools(
    *,
    registry: CapabilityRegistry,
    tools_dir: Path | str,
) -> list[str]:
    """Register generated MCP JSON tool definitions into registry handlers."""
    root = Path(tools_dir)
    if not root.exists():
        return []

    registered: list[str] = []
    for json_file in sorted(root.glob("*.json")):
        payload = json.loads(json_file.read_text(encoding="utf-8"))
        tool_name = _non_empty(payload.get("name"), "name")
        description = _non_empty(payload.get("description", "Generated MCP tool"), "description")
        binding = payload.get("binding")
        if not isinstance(binding, dict):
            raise ValueError(f"invalid binding in {json_file}")

        async def _tool_handler(_binding: dict[str, Any] = binding, **kwargs: Any) -> dict[str, Any]:
            return {
                "status": "generated",
                "binding": _binding,
                "arguments": kwargs,
            }

        _tool_handler.__doc__ = description
        registry.register_handler(tool_name, _tool_handler)
        registered.append(tool_name)
    return registered


def _non_empty(value: Any, field: str) -> str:
    if not isinstance(value, str):
        raise ValueError(f"{field} must be a non-empty string")
    normalized = value.strip()
    if not normalized:
        raise ValueError(f"{field} must be a non-empty string")
    return normalized
