-- OwlClaw db-change NOTIFY trigger template
-- Generated by: owlclaw trigger template db-change

CREATE OR REPLACE FUNCTION {{FUNCTION_NAME}}()
RETURNS trigger AS $$
BEGIN
    PERFORM pg_notify('{{CHANNEL}}', json_build_object(
        'operation', TG_OP,
        'table', TG_TABLE_NAME,
        'id', COALESCE(NEW.id, OLD.id),
        'data', row_to_json(COALESCE(NEW, OLD))
    )::text);
    RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS {{TRIGGER_NAME}} ON {{TABLE_NAME}};
CREATE TRIGGER {{TRIGGER_NAME}}
    AFTER INSERT OR UPDATE OR DELETE ON {{TABLE_NAME}}
    FOR EACH ROW EXECUTE FUNCTION {{FUNCTION_NAME}}();
